### ISSUE TITLE
InvalidOperation exception in smartmon.py

### ISSUE THREAD

**Issue by cubranic** [prometheus-community/node-exporter-textfile-collector-scripts#37]
```
# HELP smartmon_attr_threshold SMART metric attr_threshold
# TYPE smartmon_attr_threshold gauge
Traceback (most recent call last):
  File "smartmon.py", line 378, in <module>
    main()
  File "smartmon.py", line 375, in main
    metric_print(m, 'smartmon_')
  File "smartmon.py", line 115, in metric_print
    print(metric_format(metric, prefix))
  File "smartmon.py", line 101, in metric_format
    value = decimal.Decimal(metric.value)
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
```

**Comment by tonin** [comment]
Might be solved by #41

**Comment by dswarbrick** [comment]
> Might be solved by #41

@cubranic Can you please confirm whether this is now working with master?
